# docker compose up -d

version: '3.9'
services:
  database:
    image: postgres:15.3
    restart: always
    env_file:
      - ./database/.env # required - needs to contain POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '6432:5432'
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: /database/healthcheck.sh
      interval: "10s"

  web:
    restart: always
    env_file:
      - ./database/.env
    build:
      context: ./web
    depends_on:
      - database
    ports:
      - '5000:5000'

# container for running post-deploy smoke tests
# container exits after test are completed
# note that the tests update state (new executions are added to the database)
# it's ok to comment out this service
  smoke:
    build:
      context: ./smoke
    network_mode: "host"  
    depends_on:
      - web
